table enrolment_0_500000
	lineageTag: 04dfe95b-da3e-4158-9b28-4b9fafb70aba

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a166e835-d772-4209-a8a2-ec1f6fc867eb
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column state
		dataType: string
		lineageTag: 15d5e76b-cfe9-4a49-821e-f9cf701aed14
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column district
		dataType: string
		lineageTag: a3dad796-84b1-4d9e-879f-c39f7b64f472
		summarizeBy: none
		sourceColumn: district

		annotation SummarizationSetBy = Automatic

	column pincode
		dataType: int64
		formatString: 0
		lineageTag: 70193536-89f8-4328-9929-7d64e0ad9c98
		summarizeBy: sum
		sourceColumn: pincode

		annotation SummarizationSetBy = Automatic

	column age_0_5
		dataType: int64
		formatString: 0
		lineageTag: 85ae48a1-84ec-420a-973b-9288557de0af
		summarizeBy: sum
		sourceColumn: age_0_5

		annotation SummarizationSetBy = Automatic

	column age_5_17
		dataType: int64
		formatString: 0
		lineageTag: 54f32048-9693-43cd-99f0-11a3bd0e1051
		summarizeBy: sum
		sourceColumn: age_5_17

		annotation SummarizationSetBy = Automatic

	column age_18_greater
		dataType: int64
		formatString: 0
		lineageTag: 3b1c4e7b-4cec-4ff5-a6dc-db168864df2d
		summarizeBy: sum
		sourceColumn: age_18_greater

		annotation SummarizationSetBy = Automatic

	partition enrolment_0_500000 = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\hp\Downloads\api_data_aadhar_enrolment\api_data_aadhar_enrolment\api_data_aadhar_enrolment_0_500000.csv"),[Delimiter=",", Columns=7, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"date", type date}, {"state", type text}, {"district", type text}, {"pincode", Int64.Type}, {"age_0_5", Int64.Type}, {"age_5_17", Int64.Type}, {"age_18_greater", Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Change Type", each true),
				    #"Changed Type" = Table.TransformColumnTypes(#"Filtered Rows",{{"state", type text}}),
				    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each true)
				in
				    #"Filtered Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

